# Generated by Django 4.2 on 2023-04-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentid',
            options={'ordering': ['student_id']},
        ),
    ]
