# Generated by Django 4.2 on 2023-04-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmarks',
            options={'verbose_name_plural': 'Subject Marks'},
        ),
    ]
